### ISSUE TITLE
Description of the variables

### ISSUE THREAD

**Issue by durraniu** [agargcode001/CarFollowingModels#1]
Hi,

Thank you for sharing your work. I am trying to understand the random forest regressor that you used in the notebook. Could you please let me know what the variables in the excel files mean? For example, you are predicting `Sp2` in the `df1` dataset. What is `Sp2`?

Thank you again and best regards.

**Comment by darshansiddhpura** [comment]
for df 1
![image](https://user-images.githubusercontent.com/73816107/159188142-17e38099-4889-4eb1-a180-b7080bb777ec.png)

>> he took a speed 4s second value as the first value of sp2 and the rest of the columns continue.......
for df2
![image](https://user-images.githubusercontent.com/73816107/159188196-65c84146-9dbf-4e21-8dbf-02d1acd1b984.png)

>> he took a speed 2s second value as the first value of sp2 and the rest of the columns continued.......

**Comment by bhupesh-reddy** [comment]
Hi ,

It seems that he has created a column with a shifted value of the first following vehicle's speed(speed2) inorder to predict the speed of the vehicle in the next instance(time).

**Comment by durraniu** [comment]
@darshansiddhpura and @bhupesh-reddy thank you. Yes, I also figured that the author has used lagged speed.
